### ISSUE TITLE
Relation to mbeddr mps-gradle-plugin

### ISSUE THREAD

**Issue by ftomassetti** [specificlanguages/mps-gradle-plugin#4]
How this plugin relates to [the one from the mbeddr project](https://github.com/mbeddr/mps-gradle-plugin)?
They have the same name and perhaps share some of the same tasks

**Comment by sergej-koscejev** [comment]
They have the same name, don't share any tasks, however this plugin relies on (a part of) the mbeddr plugin for some functionality.

**Comment by sergej-koscejev** [comment]
This plugin's vision is to be opinionated but simple: you give up flexibility but gain ease of use.
